### ISSUE TITLE
[Suggestion] Categories for Applications as well

### ISSUE THREAD

**Issue by beyertom** [pawelmalak/flame#54] opened 2021-06-25 13:53 UTC
Hi,

is it possible to add categories to the applications as well? As an example you can take a look at Homer (https://github.com/bastienwirtz/homer).

Thank you!

Cheers

**Comment by gitcatpeter** [comment] 2021-06-25 15:58
Second that. I know the developer sad "no" before, but maybe he could reconsider (make this on/off option).
Again, thank you for the work Pawel.

**Comment by pawelmalak** [comment] 2021-08-04 22:36
Duplicate of #7 and #32.
You can check out [fdarveau/flame](https://github.com/fdarveau/flame) for this feature.

**Closed by pawelmalak** 2021-08-04 22:36 UTC
Labels: duplicate
