### ISSUE TITLE
[Feature Request] Hide URL's

### ISSUE THREAD

**Issue by Tyrian81** [pawelmalak/flame#232] opened 2021-11-28 06:46 UTC
Your flame dashboard is amazing, very clean and simple.

Although i would love the ability to hide the URL's under applications.
It would make it even cleaner for me :)

kind regards

**Comment by nomandera** [comment] 2021-11-28 09:08
https://github.com/pawelmalak/flame/issues/197#issuecomment-972928673

**Comment by pawelmalak** [comment] 2021-11-29 21:13
Duplicate of #105

**Closed by pawelmalak** 2021-11-29 21:13 UTC
Labels: 💣 Duplicate
