### ISSUE TITLE
Allow custom search engine

### ISSUE THREAD

**Issue by AzamServer** [pawelmalak/flame#82] opened 2021-09-03 22:35 UTC
I do know Flame does support different search engines within the search bar, but I was wondering if there's a way to add a custom search engine (using a custom search engine URL), like a self-hosted Whoogle instance. If this is possible, please let me know.

**Comment by pawelmalak** [comment] 2021-09-06 21:56
Duplicate of #71

**Closed by pawelmalak** 2021-09-06 21:56 UTC
Labels: duplicate

**Comment by firestrife23** [comment] 2021-10-04 14:34
it's not duplicate, I run my own self host search engine at https://searx.n0where.io which is not exposed to public but to my own LAN, so I don't see a way I can I add that.

**Comment by pawelmalak** [comment] 2021-10-04 14:39
It's a duplicate. #71 proposes feature which would allow to add custom search engine with custom prefix and query template same as this.
