### ISSUE TITLE
Hide Application URLs

### ISSUE THREAD

**Issue by MichiFr** [pawelmalak/flame#276] opened 2022-01-03 13:25 UTC
Hi!

Maybe I missed the obvious, but is there any setting to hide the URL that is shown under each applications name?

Thx,
Michael

**Comment by KevBelisle** [comment] 2022-01-07 22:26
You can hide it with this custom CSS:

```CSS
.AppCard_AppCardDetails__tbAhY > span {
  display: none;
}
```

**Comment by pawelmalak** [comment] 2022-01-08 11:39
Duplicate of #105

**Closed by pawelmalak** 2022-01-08 11:39 UTC
