### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by chardric** [pawelmalak/flame#268] opened 2021-12-20 08:22 UTC
May I request for a customization setting for the favicon that we can upload our own icon.
TIA.

**Comment by Teraskull** [comment] 2021-12-20 09:00
Duplicate of #185

**Comment by Brancliff** [comment] 2021-12-26 08:02
I think OP's asking moreso for changing Flame's favicon rather than the bookmark's favicon(?)

**Comment by pawelmalak** [comment] 2021-12-26 12:33
#185 is about changing Flame's favicon.

**Closed** 2021-12-26 12:33 UTC
Labels: 💣 Duplicate
