### ISSUE TITLE
[feature] custom favicon of flame

### ISSUE THREAD

**Issue by bollnh** [pawelmalak/flame#255] opened 2021-12-13 04:16 UTC
Hi, thanks for making this such awesome project, may I ask is it possible to add a feature that can custom the favicon?
I have use flame to create a quite chill dashboard but the red flame icon always make me feel it doesn't match the UI.

**Comment by pawelmalak** [comment] 2021-12-17 11:32
Duplicate of #185

**Closed by pawelmalak** 2021-12-17 11:32 UTC
Labels: 💣 Duplicate
